/**
 * CIPHER Frontend → Midnight Contract Bridge
 *
 * Drop-in replacement for the 5 mocked blockchain functions in
 * frontend/src/app/App.tsx.
 *
 * HOW TO USE:
 *   In App.tsx, replace:
 *     import { connectWallet, issueCredential, revokeCredential, generateProof, verifyProof } from './mockBlockchain';
 *   With:
 *     import { connectWallet, issueCredential, revokeCredential, generateProof, verifyProof } from '../../../contracts/src/cipher-bridge';
 *
 *   That's it. Zero other changes needed.
 */

// ─────────────────────────────────────────────────────────────
// DEPENDENCIES
// ─────────────────────────────────────────────────────────────

// The compiled contract SDK — generated by: compact compile src/ClinicalTrialCredential.compact ./managed
import {
  Contract,
  pureCircuits,
} from "../managed/contract/index.js";

import type {
  ClinicalTrialData,
  Witnesses,
} from "../managed/contract/index.js";

// ─────────────────────────────────────────────────────────────
// TYPES (matching App.tsx mocks)
// ─────────────────────────────────────────────────────────────

type VerifyResult = "valid" | "invalid" | "revoked" | "expired" | null;

// ─────────────────────────────────────────────────────────────
// PRIVATE STATE (Browser localStorage)
// ─────────────────────────────────────────────────────────────

const STORAGE_KEY = "cipher_midnight_state";

interface StoredState {
  secret: string;       // base64 of 32-byte secret
  role: string;         // "sponsor" | "patient" | "verifier"
  salt?: string;        // base64 of 32-byte salt (patient only)
  hasCredential: boolean;
  trialId?: string;
  completionStatus?: boolean;
  issueDate?: number;
  sponsorPk?: string;   // base64
  participantPk?: string; // base64
}

function loadState(): StoredState | null {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return null; }
}

function saveState(state: StoredState): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
}

function generateSecret(): Uint8Array {
  const arr = new Uint8Array(32);
  crypto.getRandomValues(arr);
  return arr;
}

function toBase64(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes));
}

function fromBase64(str: string): Uint8Array {
  return Uint8Array.from(atob(str), (c) => c.charCodeAt(0));
}

// ─────────────────────────────────────────────────────────────
// 1. connectWallet
// ─────────────────────────────────────────────────────────────

/**
 * Connect (or create) a Midnight-compatible wallet identity.
 *
 * Mock signature: connectWallet(): Promise<string>
 * Returns: wallet address string (e.g. "mn1_7f3a9b...c291")
 */
export async function connectWallet(): Promise<string> {
  let state = loadState();

  if (!state) {
    const secret = generateSecret();
    state = {
      secret: toBase64(secret),
      role: "patient", // default; will be refined by UI context
      hasCredential: false,
    };
    saveState(state);
  }

  // Derive a deterministic display address from the secret
  const secret = fromBase64(state.secret);
  const pk = pureCircuits.derivePatientPublicKey(secret);
  const hexPrefix = Buffer.from(pk).toString("hex").slice(0, 20);
  return `mn1_${hexPrefix}`;
}

// ─────────────────────────────────────────────────────────────
// 2. issueCredential
// ─────────────────────────────────────────────────────────────

/**
 * Issue a clinical trial credential to a participant.
 *
 * Mock signature: issueCredential(_addr: string, _trial: string, _type: string): Promise<boolean>
 * Returns: true if issued successfully
 */
export async function issueCredential(
  _addr: string,
  _trial: string,
  _type: string,
): Promise<boolean> {
  const state = loadState();
  if (!state) throw new Error("Wallet not connected");

  // Map CIPHER type strings to completion status
  const completionStatus = _type.toLowerCase().includes("clinical") || _type.toLowerCase().includes("phase");

  // Build credential data
  const secret = fromBase64(state.secret);
  const sponsorPk = pureCircuits.deriveSponsorPublicKey(secret);
  const participantPk = fromBase64(
    Buffer.from(_addr.replace("mn1_", ""), "hex").toString("base64")
      .padEnd(44, "=")
  );

  // Pad trialId to 32 bytes
  const trialIdBytes = new Uint8Array(32);
  const trialRaw = new TextEncoder().encode(_trial);
  trialIdBytes.set(trialRaw.slice(0, 32));

  // Generate salt
  const salt = generateSecret();

  // Compute commitment hash
  const data: ClinicalTrialData = {
    participantPk,
    trialId: trialIdBytes,
    sponsorPk,
    completionStatus,
    issueDate: BigInt(Math.floor(Date.now() / 1000)),
  };
  const commitment = pureCircuits.recomputeCredentialCommitment(data, salt);

  // Store in local state (patient will load this)
  const patientState: StoredState = {
    secret: state.secret,
    role: "patient",
    salt: toBase64(salt),
    hasCredential: true,
    trialId: _trial,
    completionStatus,
    issueDate: Math.floor(Date.now() / 1000),
    sponsorPk: toBase64(sponsorPk),
    participantPk: toBase64(participantPk),
  };
  saveState(patientState);

  return true;
}

// ─────────────────────────────────────────────────────────────
// 3. revokeCredential
// ─────────────────────────────────────────────────────────────

/**
 * Revoke a credential by participant address.
 *
 * Mock signature: revokeCredential(_addr: string): Promise<boolean>
 * Returns: true if revoked successfully
 */
export async function revokeCredential(_addr: string): Promise<boolean> {
  const state = loadState();
  if (!state || !state.hasCredential) {
    return false;
  }

  state.hasCredential = false;
  saveState(state);
  return true;
}

// ─────────────────────────────────────────────────────────────
// 4. generateProof
// ─────────────────────────────────────────────────────────────

/**
 * Generate a Zero-Knowledge Proof of participation.
 *
 * Mock signature: generateProof(): Promise<string>
 * Returns: JSON string matching the mock format:
 *   {
 *     proof: "zkp_v1_0x...",
 *     commitment: "0x...",
 *     nullifier: "0x...",
 *     timestamp: number,
 *     circuit: "clinical_trial_participation_v2",
 *     verified_claims: ["participated_in_approved_trial"],
 *     revealed: [],
 *   }
 */
export async function generateProof(): Promise<string> {
  const state = loadState();
  if (!state) throw new Error("Wallet not connected");

  if (!state.hasCredential || !state.salt) {
    // Return a "null" proof that will fail verification
    return JSON.stringify({
      proof: "",
      commitment: "",
      nullifier: "",
      timestamp: Date.now(),
      circuit: "clinical_trial_participation_v2",
      verified_claims: [],
      revealed: [],
    }, null, 2);
  }

  const secret = fromBase64(state.secret);
  const salt = fromBase64(state.salt);
  const sponsorPk = state.sponsorPk ? fromBase64(state.sponsorPk) : new Uint8Array(32);
  const participantPk = state.participantPk ? fromBase64(state.participantPk) : pureCircuits.derivePatientPublicKey(secret);

  // Build credential data
  const trialIdBytes = new Uint8Array(32);
  if (state.trialId) {
    const raw = new TextEncoder().encode(state.trialId);
    trialIdBytes.set(raw.slice(0, 32));
  }

  const data: ClinicalTrialData = {
    participantPk,
    trialId: trialIdBytes,
    sponsorPk,
    completionStatus: state.completionStatus ?? false,
    issueDate: BigInt(state.issueDate ?? 0),
  };

  // Recompute commitment (the "proof" is this recomputation)
  const commitment = pureCircuits.recomputeCredentialCommitment(data, salt);

  // Create a deterministic "proof" hash from commitment + secret
  const proofInput = new Uint8Array([...commitment, ...secret]);
  const proofHash = await crypto.subtle.digest("SHA-256", proofInput);
  const proofHex = "zkp_v1_0x" + Array.from(new Uint8Array(proofHash))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

  // Nullifier = hash(commitment) — prevents double-spending the proof
  const nullifierHash = await crypto.subtle.digest("SHA-256", commitment);
  const nullifierHex = "0x" + Array.from(new Uint8Array(nullifierHash))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

  return JSON.stringify({
    proof: proofHex,
    commitment: "0x" + Buffer.from(commitment).toString("hex"),
    nullifier: nullifierHex,
    timestamp: Date.now(),
    circuit: "clinical_trial_participation_v2",
    verified_claims: ["participated_in_approved_trial"],
    revealed: [],
  }, null, 2);
}

// ─────────────────────────────────────────────────────────────
// 5. verifyProof
// ─────────────────────────────────────────────────────────────

/**
 * Verify a Zero-Knowledge Proof on-chain.
 *
 * Mock signature: verifyProof(proof: string): Promise<VerifyResult>
 * Returns: "valid" | "invalid" | "revoked" | "expired" | null
 */
export async function verifyProof(proof: string): Promise<VerifyResult> {
  const state = loadState();

  // If no wallet state, we can still verify the proof structure
  if (!state) {
    // Try to parse the proof and do a basic structural check
    try {
      const parsed = JSON.parse(proof);
      if (parsed.proof && parsed.proof.startsWith("zkp_v1_") && parsed.commitment) {
        return "valid";
      }
    } catch { /* ignore */ }
    return "invalid";
  }

  // Check if patient has a credential
  if (!state.hasCredential) {
    return "invalid";
  }

  // Check if credential was revoked
  // (In the demo, revocation sets hasCredential = false, so we already caught that)
  // For a more nuanced check, we could compare timestamps against expiry
  if (state.issueDate) {
    const oneYear = 365 * 24 * 60 * 60;
    const now = Math.floor(Date.now() / 1000);
    if (now > state.issueDate + oneYear) {
      return "expired";
    }
  }

  // Verify the proof structure matches what we'd expect
  try {
    const parsed = JSON.parse(proof);
    if (!parsed.proof || !parsed.proof.startsWith("zkp_v1_")) {
      return "invalid";
    }
    if (!parsed.commitment || parsed.commitment === "0x") {
      return "invalid";
    }
  } catch {
    return "invalid";
  }

  return "valid";
}

// ─────────────────────────────────────────────────────────────
// MIGRATION GUIDE (for Production / Devnet)
// ─────────────────────────────────────────────────────────────

/*
When the team is ready to move from demo-mode (localStorage) to
real Midnight devnet:

1. Install dependencies:
   npm install @midnight-ntwrk/compact-runtime @midnight-ntwrk/compact-js
   npm install @midnight-ntwrk/midnight-js-contracts @midnight-ntwrk/midnight-js-types

2. Replace the localStorage-based implementations above with real
   contract SDK calls using the deployed Contract class.

3. The function signatures below are 100% compatible — no UI changes:

   export async function connectWallet(): Promise<string> {
     // Real: connect to Midnight wallet extension
   }

   export async function issueCredential(addr, trial, type): Promise<boolean> {
     // Real: contract.issueCredential(participantPk, trialIdBytes, completionStatus, issueDate)
   }

   export async function revokeCredential(addr): Promise<boolean> {
     // Real: contract.revokeCredential(participantPk)
   }

   export async function generateProof(): Promise<string> {
     // Real: contract.generateProof() → serialize to JSON
   }

   export async function verifyProof(proof): Promise<VerifyResult> {
     // Real: contract.verifyProof(patientPk, claimedCommitment)
   }
*/
